### ISSUE TITLE
Fails on empty resources directory

### ISSUE THREAD

**Issue by matthazinski** [andreimarcu/ScholarRetriever#3]
[matt@teselecta ScholarRetriever]$ python2 scholar_retriever.py 
Password: 
Traceback (most recent call last):
  File "scholar_retriever.py", line 70, in <module>
    sr.get_classes()
  File "scholar_retriever.py", line 26, in get_classes
    self.get_class(c[0], c[1])
  File "scholar_retriever.py", line 61, in get_class
    get_contents()
  File "scholar_retriever.py", line 41, in get_contents
    get_contents(bare)
  File "scholar_retriever.py", line 41, in get_contents
    get_contents(bare)
  File "scholar_retriever.py", line 36, in get_contents
    for e in self.w.ls(path)[1:]:
  File "/usr/lib/python2.7/site-packages/easywebdav/client.py", line 176, in ls
    response = self._send('PROPFIND', remote_path, (207, 301), headers=headers)
  File "/usr/lib/python2.7/site-packages/easywebdav/client.py", line 100, in _send
    raise OperationFailed(method, path, expected_code, response.status_code)
easywebdav.client.OperationFailed: Failed to list directory "Team 7".
  Operation     :  PROPFIND Team 7
  Expected code :  207 UNKNOWN, 301 Moved Permanently
  Actual code   :  404 Not Found

**Comment by andreimarcu** [comment]
Thanks for the bug report.
